"""update order item relation

Revision ID: a56f986d52e2
Revises: f9b81e70c905
Create Date: 2022-01-02 13:45:21.643151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a56f986d52e2"
down_revision = "f9b81e70c905"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_item_food_id_fkey", "order_item", type_="foreignkey")
    op.create_foreign_key(None, "order_item", "food", ["food_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_item", type_="foreignkey")
    op.create_foreign_key(
        "order_item_food_id_fkey", "order_item", "category", ["food_id"], ["id"]
    )
    # ### end Alembic commands ###
